/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Flavio Horita' at '14/11/16 14:50' with Gradle 2.14
 *
 * @author Flavio Horita, @date 14/11/16 14:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
